apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: kubtask
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: kubtask
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: kubtask

    spec:
      containers:
      - name: postgres
        image: postgres:9.5
        ports:
        - containerPort: 5432
