apiVersion: v1
kind: Service
metadata:
  name: sentry-service
  labels:
    name: kubsentry-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9000
  selector:
    app: kubtasksentry
