apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry
  labels:
    name: kubtasksentry
    
spec:
  replicas: 1
    selector:
       matchLabels: 
          app: kubtasksentry        
  template:
    metadata:
      labels:
        app: kubtasksentry
    spec:
      containers:

      - name: redis
        image: redis:3.2-alpine
        
      - name: postgres
        image: postgres:9.5
        env:
          - name: POSTGRES_PASSWORD
            value: sentry
          - name: POSTGRES_USE
            value: sentry
        
      - name: sentry
        image: sentry-onpremise
        args:
        - run
        - web
        ports:
        - containerPort: 9000
            
      - name: worker
        image: sentry-onpremise
        args:
        - run
        - worker
        
      - name: cron
        image: sentry-onpremise
        args:
        - run
        - cron
      

     
